--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/r3pt1s/GroupSystem
build-by-default: true
branches:
- main
projects:
  GroupSystem:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
      - src: poggit/libasynql/libasynql
        version: ^4.1.6
...