--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/r3pt1s/GroupSystem
build-by-default: true
branches:
- main
projects:
  GroupSystem:
    path: ""
    libs:
      - src: r3pt1s/BetterForms/BetterForms
        version: 1.0.0
      - src: poggit/libasynql/libasynql
        version: ^4.2.3
...