name: GroupSystem
version: 3.4.0
api: 5.0.0
main: r3pt1s\groupsystem\GroupSystem
author: r3pt1s
load: STARTUP

permissions:
  groupsystem.groupinfo.command:
    default: true
  groupsystem.group.command:
    default: op